name: Update Sources

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**.pac'
  workflow_dispatch:

jobs:
  minify:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          npm install -g uglify-js

      - name: Minify files
        run: |
          cd src/ 
          for file in *.pac; do
            uglifyjs --comments all $file > ../PAC/$file
          done

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'PAC'
          default_author: github_actions
          message: 'Minify PAC files'