name: Update Sources

on:
  push:
    branches:
      - 'main'
    paths:
      - '/src/**.pac'
  workflow_dispatch:

jobs:
  minify:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          npm install -g uglify-js

      - name: Minify files
        run: |
          for file in ./src/*.pac; do
            uglifyjs --comments all ./src/$file > ./PAC/$file
          done

      - name: Commit changes
        run: |
          git add .
          git diff-index --quiet HEAD || (git commit -m "Minify files" && git push)